services:
  servicescomplexe-db-container:
    image: bitnami/mysql:latest
    container_name: servicescomplexe-db-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: servicescomplexe-database
      MYSQL_USER: admin
      MYSQL_PASSWORD: changeme
    ports:
      - 3306:3306
    volumes:
      - ./bdd/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./bdd/mysql_data/:/bitnami/mysql/data/
    networks:
      - servicescomplexe-network

  servicescomplexe-phpmyadmin-container:
    image: phpmyadmin/phpmyadmin
    container_name: servicescomplexe-phpmyadmin-container
    restart: always
    environment:
      PMA_HOST: servicescomplexe-db-container
      MYSQL_ROOT_PASSWORD: changeme
    networks:
      - servicescomplexe-network

volumes:
  mysql_data:

networks:
  servicescomplexe-network:
    external: true
