version: '3.8'

services:
  apache:
    image: httpd:latest
    container_name: apache
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - ./apache/conf:/usr/local/apache2/conf
      - ./apache/html:/usr/local/apache2/htdocs
      - ./apache/logs:/var/log/apache2
    environment:
      - DOMAINE_NAME=${DOMAINE_NAME}
      - APACHE_ADMIN_USER=${APACHE_ADMIN_USER}
      - APACHE_ADMIN_PASSWORD=${APACHE_ADMIN_PASSWORD}
    depends_on:
      - mysql
    networks:
      - web-network

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - web-network

  php:
    image: php:7.4-fpm
    container_name: php
    ports:
      - "${PHP_PORT}:9000"
    volumes:
      - ./php/conf:/usr/local/etc/php
      - ./php/logs:/var/log/php
    networks:
      - web-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: ${PHPMYADMIN_ADMIN_USER}
      PMA_PASSWORD: ${PHPMYADMIN_ADMIN_PASSWORD}
    depends_on:
      - mysql
    networks:
      - web-network

volumes:
  mysql_data:

networks:
  web-network:
    external: true