
version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: servicescomplexe-db-container
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: servicescomplexe-database
      MYSQL_USER: admin
      MYSQL_PASSWORD: changeme
    networks:
      - servicescomplexe-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: servicescomplexe-phpmyadmin-container
    ports:
      - "81:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: changeme
      PMA_USER: admin
      PMA_PASSWORD: changeme
    depends_on:
      - mysql
    networks:
      - servicescomplexe-network
      
  web:
    image: php:7.4-apache
    container_name: servicescomplexe-web-container
    ports:
      - "79:9000"
    volumes:
      - ./www:/var/www/html
      - ./apache2:/etc/apache2/
    depends_on:
      - mysql
    networks:
      - servicescomplexe-network

volumes:
  mysql_data:

networks:
  servicescomplexe-network:
    external: true
